#ifndef ASTEROIDS_CONSTANTS_H
#define ASTEROIDS_CONSTANTS_H

#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 600
#define SCREEN_CENTER CLITERAL(Vector2){(float)SCREEN_WIDTH / 2, (float)SCREEN_HEIGHT / 2}

#define NEARBLACK CLITERAL(Color){15, 15, 15, 255}

#define ASTEROIDS_MAX 64
#define ASTEROID_RANDOM_ANGLE (20 * DEG2RAD)
#define ASTEROID_DELAY 1.0f

#endif
